# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.2

# Services that will be used
# services:
  # - mysql

# Commands to be run before your environment runs.
before_script:
  # Setup ENV
  - cp .env.travis .env
  # - mysql -e 'create database countries_testing;'
  #
  # Install Dependencies
  - composer self-update
  - composer install --no-interaction
  - composer run-script post-create-project-cmd  # Generate App Key, etc
  #
  # Test: Inspect PhpUnit version
  # Version on CI server
  - phpunit --version
  # Version on Project Deps
  - ./vendor/bin/phpunit --version

# Commands you want to run that will verify your build.
script:
  # PHPUnit
  # - Do NOT run just "phpunit" except you want the CI build machine to run an updated version of PHPUnit (8.0.2 at this time)
  # - For compatibility, run "./vendor/bin/phpunit" to run the exact version used in your project (7.5.3 at this time)
  - ./vendor/bin/phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 7.2
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
  email:
    recipients:
      - deciano.cn@gmail.com
    on_success: always
    on_failure: always
